import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Optional Finance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/optional.svg" />
      </Head>
      <main className={styles.main}>
        <nav className={styles.inline}>
          <div className={styles.nav}>
            <img className={styles.icon} src='/optional.svg' width="50px" height="60px"></img>
              <div className={styles.links}>
                <a href="/">Home</a>
                <a>Trade</a>
                <a>Manager</a>
                <a>Docs</a>
              </div>
              <button className={styles.connectbtn}>Connect </button>
            </div>  
              
        </nav>
        <p className={styles.title}>
          Decentralized Social<br></br> Trading for Options
        </p>
        <div className={styles.tagline}>
          <p className={`${styles.inline} ${styles.desc}`}>
            <span>You Deposit. They Trade.</span>  <span className={styles.purp}>You Earn.</span>
          </p>
          
        </div>
        <button className={styles.launchbtn}>
          Launch App
        </button>
        <div className={styles.cardscontainer}>
          <div className={styles.cards}>
            <div className={styles.venusicon}>
              <img className={styles.venus}src="/venus_square 1.png" ></img>
            </div>
            <div>
              <p className={styles.cardname}>Venus</p>
              <p className={styles.cardat}>@Venus</p>
            </div>
            
          </div>
        </div>

        <p className={styles.title}>About Optional</p>
        <div>
          <div className={styles.optionsdesc}>
            <div>
              <p className={styles.optionstitle}> Exposure to Options</p>
              <p>Optional allows both social traders and their followers to expose themselves to the options market utilizing decentralized option protocols like Opyn.</p>
            </div>
            <div className={styles.optionsicon}>
              <img className={styles.opyn}src="/image 5.png" ></img>
            </div>
          </div>
          <div className={styles.earndesc}>
            <div className={styles.earnicon}>
              <img className={styles.earn}src="/Vector.png" ></img>
            </div>
            <div>
              <p className={styles.optionstitle}> Earn Yield for Followers,<br></br> Earn Fees for Yourself</p>
              <p>Social traders can earn fees for themselves in a variety of ways, especially if their performance is exceptional!</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
