import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Optional Finance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/optional.svg" />
      </Head>
      <main className={styles.main}>
        <nav className={styles.inline}>
          <div className={styles.nav}>
            <img className={styles.icon} src='/optional.svg' width="50px" height="60px"></img>
              <div className={styles.links}>
                <a href="/">Home</a>
                <a>Trade</a>
                <a>Manager</a>
                <a>Docs</a>
              </div>
              <button className={styles.connectbtn}>Connect </button>
            </div>  
              
        </nav>
        <p className={styles.title}>
          Decentralized Social<br></br> Trading for Options
        </p>
        <div className={styles.tagline}>
          <p className={`${styles.inline} ${styles.desc}`}>
            <span>You Deposit. They Trade.</span>  <span className={styles.purp}>You Earn.</span>
          </p>
          
        </div>

        <div className={styles.cardscontainer}>
          <div className={styles.cards}>
            <p>Venus</p>
            <p>@Venus</p>
          </div>
          <div className={styles.cards}>
            <p>AAAA</p>
          </div>
          <div className={styles.cards}>
            <p>AAAA</p>
          </div>
        </div>
      </main>

    </div>
  )
}
